### ISSUE TITLE
Problemes dans la remontee des notes sur Moodle

### ISSUE THREAD

**Issue by toccata10** [suipnice/moodle-mod_wims#10]
Bonjour,
A l'ulco, on a recemment mis en place le plugin.
Cela semble fonctionner correctement (creation automatique des classes par ex), a l'exception de la remontee des notes:
Voici un exemple: je ne vois pas de rapport entre le resultat wims et la note sur moodle + les remontees sur moodle semblent etre a 10 au max (meme si config sur 20 dans wims).
Une piste ?
![01-details](https://github.com/suipnice/moodle-mod_wims/assets/7478580/5328ac34-88f6-44a6-b9b7-819b25f840ca)
![02-global](https://github.com/suipnice/moodle-mod_wims/assets/7478580/728490d1-33e3-45f0-ad0c-33450ceb7cbb)
![03-config](https://github.com/suipnice/moodle-mod_wims/assets/7478580/15fc4a00-13dc-438d-8548-e2a6805c3e87)
![04-Moodle](https://github.com/suipnice/moodle-mod_wims/assets/7478580/25e3be52-00dd-4c7f-b38b-cb64fa4f9bf4)

**Comment by Badatos** [comment]
Bonjour,
En effet les notes remontées à Moodle sont des notes "brutes" données par WIMS, sans recalcul. Ce sont donc toujours les notes initiales sur 10. Pour plus de cohérence entre les 2 plateformes, il est donc préférables de laisser les notes sur 10 coté WIMS et de faire ensuite d'éventuels recalculs côté Moodle.

**Comment by Badatos** [comment]
Bonjour,
En effet les notes remontées à Moodle sont des notes "brutes" données par WIMS, sans recalcul. Ce sont donc toujours les notes initiales sur 10. Pour plus de cohérence entre les 2 plateformes, il est donc préférable de laisser les notes sur 10 coté WIMS et de faire ensuite d'éventuels recalculs côté Moodle.

**Comment by toccata10** [comment]
Bonjour,
J'ai refait mon parametrage en laissant les notes sur 10 sur Wims.
Cela semble remonter la reussite (multipliee par 0.1) et pas la note. Or ce qui m'interesse, c'est la note.
Y a-t-il un parametrage a faire (ou alors c'est moi qui n'ai pas compris qqechose) ?
gimp_qcm01 est un qcm pour lequel je demande d'obtenir 40 pts (soit 4 repetitions du qcm parfaitement reussies pour obtenir la note maximale).
![Screenshot from 2024-08-27 08-09-14](https://github.com/user-attachments/assets/440453b3-992c-48c0-b99a-c4ac1d6631f9)
![Screenshot from 2024-08-27 08-16-58](https://github.com/user-attachments/assets/815b278a-dac4-4059-ae71-b053f8b8521f)

**Comment by Badatos** [comment]
Coté WIMS, on voit en effet 3 scores pour la feuille, par exemple :

- Note: 2.9 / 10
- Qualité: 7.73 /10
- Cumul: 33 %

Malheuresement, le webservice de WIMS ne fournit que 2 de ces scores (qualité et cumul), pas la note. Exemple de résultat fourni par WIMS :
```json
{
  "status": "OK",
  "job": "getsheetscores",
  "query_sheet": 2,
  "query_class": "1001002",
  "sheet_mean_quality": 7.73,
  "sheet_mean_percent": 33,
  "sheet_max_quality": 7.73,
  "sheet_max_percent": 33,
}
```

**Comment by toccata10** [comment]
Du coup, autant pour la creation de classe, c'est vraiment tres bien, autant je ne vois pas l'interet de la remontee des notes sur Moodle (pour les feuilles d'exos en tout cas), car, si je comprends bien:
1) on remonte le cumul: donc un etudiant qui ferait 10 fois un exo en ne decrochant que 1/10 a chaque fois aurait 10, soit 100% de cumul
2) pour calculer la note, on a besoin de la reussite et de la qualite.
Je reprends l'exemple base sur cette doc:
https://hotellerie-restauration.ac-normandie.fr/sites/maths-caen.second-degre.ac-normandie.fr/IMG/pdf/SuivreTravailEleves.pdf

reussite : 94 % ; qualité 7,36 / 10. Pour une note avec une severite de 3, la note est obtenue par:
10 × 0,94 × 0,736^0,5 = 8.06 (sur 10)

Y a-t-il un espoir que la note et/ou que les valeurs de reussite et de qualite soient remontees par le plugin ?
Merci

**Comment by toccata10** [comment]
OK. Je vais completer mon message sur le forum, des fois q'un dev ait un peu de temps pour ajouter soit la note (idealement), soit la reussite.

**Comment by Badatos** [comment]
Il me semble que la réussite, c'est justement ce qui est affiché actuellement.

**Comment by toccata10** [comment]
D'apres la feuille2, test2, c'est le cumul (ce qui ne semble semble vraiment pas interessant). Si on arrivait juste a remonter la qualite et la reussite dans Moodle, on pourrait se debrouiller facilement avec une formule du carnet de notes.
![wims-01](https://github.com/user-attachments/assets/5b5e1ed4-74fa-4343-93ba-40b65ae650ea)
![wims-02](https://github.com/user-attachments/assets/c40b619e-a2b0-4c59-abcb-7da430e446d1)

**Comment by Badatos** [comment]
Ah oui bien vu pour le cumul.
Ceci dit, on n'arrivera jamais à remonter la qualité ET la réussite dans Moodle, seule UNE note peut être remontée dans le carnet de note. il faudra choisir entre l'une ou l'autre.

**Comment by Badatos** [comment]
Y-a-t-il une formule simple pour calculer la réussite à partir du cumul ?

**Comment by toccata10** [comment]
Non, je ne crois pas: d'apres la doc de wims:
"*L'indicateur de cumul (i0) est la somme des scores plafonnée à 10n que l'on divise par 10n
*Notons y 1≥y 2≥...≥yp les scores ordonnés par ordre décroissant. L'indicateur de réussite (i1) est la moyenne des n meilleurs scores, divisé par 10"

MAIS, je viens de decouvrir qu'on peut calculer la note de differentes manieres (definie a la creation de la feuille).
Du coup, on pourrait etre coherent entre ce qui apparait sur Wims et sur Moodle (car pour l'instant, c'est incomprehensible). Pour cela:
1) parametrer la regle de calcul a i0*q^0.5 sur la feuille
2) faire renvoyer par le plugin le resultat de user_percent*(user_quality/10)^0.5
Avantage: coherence entre l'affichage de wims et de moodle
Inconvenient: une seule formule de calcul possible (celle-la me parait pas mal car ca evite de faire plein de fois l'exo en se disant qu'a un moment on aura bon, donc qu'on va accumuler des points), mais je n'ai pas de meilleur argument pour le choix.

Pour moi, ce qui est essentiel c'est etre coherent entre ce que l'etudiant voit sur wims et ce qu'il voit sur Moodle. Je ne crois pas qu'il s'interesse + que cela au mode exact (tres complique d'ailleurs) de calcul sur Wims. En gros: 
* je reussis bien = j'ai une bonne note.
* Je fais n'importe quoi = ma note descend
* je veux me rattraper = je refais les exos correctement et ma note remonte

Ce serait possible de renvoyer user_percent*(user_quality/10)^0.5 pour les feuilles d'exos ?
![ksnip_20240827-153748](https://github.com/user-attachments/assets/66996546-def5-4284-98c6-ba0f720f417b)
![Screenshot from 2024-08-27 15-36-35](https://github.com/user-attachments/assets/c687a70c-9e8b-4ebf-8a1c-1d9fe5d0395b)
