### ISSUE TITLE
Notification into the calendar

### ISSUE THREAD

**Issue by lpoujet** [suipnice/moodle-mod_wims#4]
Hello,
I have some troubles with that plugin on Moodle 3.9. WIMS Classroom due on a specific date do not appear at all into the calendar like other Moodle activities (Test, Lesson, H5P ...)
It seems to be related to this plugin. Did anyone noticed the same ?
Best regards,
Lionel

**Comment by Badatos** [comment]
Bonjour Lionel,
Je viens de publier une nouvelle version 0.3.2 qui devrait permettre cela.
Dorénavant, lorsque vous définissez une "date d'achèvement attendu" pour la classe WIMS, celle-ci devrait apparaître dans le calendrier Moodle.
D'autre part, cette mise à jours vous permet également de choisir la règle "Les étudiants doivent afficher cette activité pour la terminer", ce qui n'était pas possible avant.

Passez une bonne journée,

**Comment by lpoujet** [comment]
Bonjour,
Avec une si bonne nouvelle, je vais effectivement passer une très belle journée !! :)
Mille mercis pour ce travail utile à de nombreux enseignants ! 🥇 
Lionel
